/** @deprecated Use DB-backed /api/hr/resources endpoints. Kept as offline fallback only. */

export const NIGERIA_STATES = [
  "Abia",
  "Adamawa",
  "Akwa Ibom",
  "Anambra",
  "Bauchi",
  "Bayelsa",
  "Benue",
  "Borno",
  "Cross River",
  "Delta",
  "Ebonyi",
  "Edo",
  "Ekiti",
  "Enugu",
  "FCT",
  "Gombe",
  "Imo",
  "Jigawa",
  "Kaduna",
  "Kano",
  "Katsina",
  "Kebbi",
  "Kogi",
  "Kwara",
  "Lagos",
  "Nasarawa",
  "Niger",
  "Ogun",
  "Ondo",
  "Osun",
  "Oyo",
  "Plateau",
  "Rivers",
  "Sokoto",
  "Taraba",
  "Yobe",
  "Zamfara",
] as const;

export type NigeriaState = (typeof NIGERIA_STATES)[number];

/** Major cities/LGAs per state — candidates can still type in "Other" flows later if needed. */
export const NIGERIA_CITIES_BY_STATE: Record<string, string[]> = {
  Abia: ["Aba", "Umuahia", "Other"],
  Adamawa: ["Yola", "Mubi", "Other"],
  "Akwa Ibom": ["Uyo", "Eket", "Other"],
  Anambra: ["Awka", "Onitsha", "Nnewi", "Other"],
  Bauchi: ["Bauchi", "Azare", "Other"],
  Bayelsa: ["Yenagoa", "Other"],
  Benue: ["Makurdi", "Gboko", "Other"],
  Borno: ["Maiduguri", "Other"],
  "Cross River": ["Calabar", "Other"],
  Delta: ["Asaba", "Warri", "Other"],
  Ebonyi: ["Abakaliki", "Other"],
  Edo: ["Benin City", "Other"],
  Ekiti: ["Ado-Ekiti", "Other"],
  Enugu: ["Enugu", "Other"],
  FCT: ["Abuja", "Gwagwalada", "Other"],
  Gombe: ["Gombe", "Other"],
  Imo: ["Owerri", "Other"],
  Jigawa: ["Dutse", "Other"],
  Kaduna: ["Kaduna", "Zaria", "Other"],
  Kano: ["Kano", "Other"],
  Katsina: ["Katsina", "Other"],
  Kebbi: ["Birnin Kebbi", "Other"],
  Kogi: ["Lokoja", "Other"],
  Kwara: ["Ilorin", "Other"],
  Lagos: ["Ikeja", "Lekki", "Victoria Island", "Surulere", "Yaba", "Ajah", "Ikorodu", "Other"],
  Nasarawa: ["Lafia", "Other"],
  Niger: ["Minna", "Other"],
  Ogun: ["Abeokuta", "Sagamu", "Other"],
  Ondo: ["Akure", "Other"],
  Osun: ["Osogbo", "Other"],
  Oyo: ["Ibadan", "Other"],
  Plateau: ["Jos", "Other"],
  Rivers: ["Port Harcourt", "Other"],
  Sokoto: ["Sokoto", "Other"],
  Taraba: ["Jalingo", "Other"],
  Yobe: ["Damaturu", "Other"],
  Zamfara: ["Gusau", "Other"],
};

export function citiesForState(state: string): string[] {
  const key = NIGERIA_STATES.find((s) => s.toLowerCase() === state.trim().toLowerCase()) ?? state.trim();
  return NIGERIA_CITIES_BY_STATE[key] ?? ["Other"];
}
