import { PDFDocument, StandardFonts, rgb } from "pdf-lib";

export type SalesReceiptPdfInput = {
  companyName: string;
  receiptNumber: string;
  title: string;
  customerName?: string | null;
  amount: number;
  currency: string;
  paymentMode?: string | null;
  depositAccount?: string | null;
  reference?: string | null;
  note?: string | null;
  issuedAt: Date;
  recordedBy?: string | null;
};

function money(currency: string, amount: number) {
  return `${currency} ${amount.toLocaleString("en-NG", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
}

export async function buildSalesReceiptPdf(input: SalesReceiptPdfInput): Promise<Uint8Array> {
  const doc = await PDFDocument.create();
  const page = doc.addPage([595, 842]);
  const { width, height } = page.getSize();
  const font = await doc.embedFont(StandardFonts.Helvetica);
  const fontBold = await doc.embedFont(StandardFonts.HelveticaBold);

  const primary = rgb(0.12, 0.23, 0.37);
  const accent = rgb(0.31, 0.27, 0.9);
  const muted = rgb(0.45, 0.45, 0.45);
  const border = rgb(0.85, 0.85, 0.85);

  page.drawRectangle({ x: 0, y: height - 120, width, height: 120, color: primary });
  page.drawText(input.companyName, { x: 48, y: height - 56, size: 18, font: fontBold, color: rgb(1, 1, 1) });
  page.drawText("OFFICIAL PAYMENT RECEIPT", {
    x: width - 260,
    y: height - 52,
    size: 11,
    font: fontBold,
    color: rgb(1, 1, 1),
  });
  page.drawText(input.receiptNumber, {
    x: width - 260,
    y: height - 70,
    size: 10,
    font,
    color: rgb(0.9, 0.9, 0.95),
  });

  let y = height - 160;
  page.drawText("Amount received", { x: 48, y, size: 10, font, color: muted });
  y -= 36;
  page.drawRectangle({ x: 48, y: y - 8, width: width - 96, height: 56, borderColor: accent, borderWidth: 2, color: rgb(0.97, 0.98, 1) });
  page.drawText(money(input.currency, input.amount), {
    x: 64,
    y: y + 14,
    size: 22,
    font: fontBold,
    color: primary,
  });

  y -= 48;
  page.drawText(input.title, { x: 48, y, size: 12, font: fontBold, color: rgb(0.1, 0.1, 0.1) });

  const rows: Array<[string, string]> = [
    ["Customer", input.customerName || "—"],
    ["Date issued", new Intl.DateTimeFormat("en-NG", { dateStyle: "long" }).format(input.issuedAt)],
    ["Payment mode", input.paymentMode || "—"],
    ["Deposit account", input.depositAccount || "—"],
    ["Reference", input.reference || "—"],
    ["Recorded by", input.recordedBy || "—"],
  ];

  y -= 28;
  page.drawLine({ start: { x: 48, y }, end: { x: width - 48, y }, thickness: 1, color: border });
  y -= 22;

  for (const [label, value] of rows) {
    page.drawText(label, { x: 48, y, size: 9, font: fontBold, color: muted });
    page.drawText(value, { x: 180, y, size: 10, font, color: rgb(0.15, 0.15, 0.15) });
    y -= 22;
  }

  if (input.note?.trim()) {
    y -= 8;
    page.drawText("Note", { x: 48, y, size: 9, font: fontBold, color: muted });
    y -= 16;
    const noteLines = wrapText(input.note.trim(), 70);
    for (const line of noteLines) {
      page.drawText(line, { x: 48, y, size: 10, font, color: rgb(0.2, 0.2, 0.2) });
      y -= 14;
    }
  }

  page.drawText("Thank you for your payment.", {
    x: 48,
    y: 72,
    size: 10,
    font,
    color: muted,
  });
  page.drawText("This receipt was generated by Realcorp.", {
    x: 48,
    y: 52,
    size: 8,
    font,
    color: rgb(0.65, 0.65, 0.65),
  });

  return doc.save();
}

function wrapText(text: string, maxLen: number): string[] {
  const words = text.split(/\s+/);
  const lines: string[] = [];
  let line = "";
  for (const word of words) {
    const next = line ? `${line} ${word}` : word;
    if (next.length > maxLen) {
      if (line) lines.push(line);
      line = word;
    } else {
      line = next;
    }
  }
  if (line) lines.push(line);
  return lines.slice(0, 6);
}

export function salesReceiptPdfFileName(receiptNumber: string) {
  return `${receiptNumber.replace(/[^a-zA-Z0-9-_]/g, "-")}.pdf`;
}
