ALTER TYPE "HrDocumentCategory" ADD VALUE IF NOT EXISTS 'EMERGENCY_CONTACT';
ALTER TYPE "HrDocumentCategory" ADD VALUE IF NOT EXISTS 'NEXT_OF_KIN';
ALTER TYPE "HrDocumentCategory" ADD VALUE IF NOT EXISTS 'HEALTH_RECORD';
ALTER TYPE "HrDocumentCategory" ADD VALUE IF NOT EXISTS 'EDUCATION';
